"""Initial migration

Revision ID: ae7f5c95fb5c
Revises: 
Create Date: 2026-03-18 10:19:54.570796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7f5c95fb5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('user_request_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('rub_amount', sa.Float(), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('eur_amount', sa.Float(), nullable=False),
    sa.Column('usd_rate', sa.Float(), nullable=False),
    sa.Column('eur_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_records_user_request_id'), 'cost_records', ['user_request_id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('usd_rub', sa.Float(), nullable=False),
    sa.Column('eur_rub', sa.Float(), nullable=False),
    sa.Column('eur_usd', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_cost_records_user_request_id'), table_name='cost_records')
    op.drop_table('cost_records')
    # ### end Alembic commands ###
